/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DualLabel.java
 *
 * Created on 22.08.2009, 18:17:32
 */

package ch.tatool.core.display.swing.panel;

import javax.swing.Icon;

/**
 *
 * @author j-rox
 */
public class DualPanel extends javax.swing.JPanel {

	private static final long serialVersionUID = -7038769717547891031L;
	
	/** Creates new form DualLabel */
    public DualPanel() {
        initComponents();
    }

    public void setLeftText(String text) {
        if (text != null && ! text.isEmpty()) {
            leftLabel.setText(text);
            leftLabel.setVisible(true);
        } else {
            leftLabel.setVisible(false);
        }
    }

    public void setRightText(String text) {
	if (text != null && ! text.isEmpty()) {
            rightLabel.setText(text);
            rightLabel.setVisible(true);
        } else {
            rightLabel.setVisible(false);
        }
    }

    public void setLeftIcon(Icon img) {
	if (img != null) {
	    leftLabel.setIcon(img);
	    leftLabel.setVisible(true);
        } else {
            leftLabel.setVisible(false);
        }
    }

    public void setRightIcon(Icon img) {
	if (img != null) {
	    rightLabel.setIcon(img);
	    rightLabel.setVisible(true);
        } else {
            rightLabel.setVisible(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftLabel = new javax.swing.JLabel();
        rightLabel = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.GridLayout(1, 3, 30, 0));

        leftLabel.setFont(leftLabel.getFont().deriveFont(leftLabel.getFont().getSize()+30f));
        leftLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        add(leftLabel);

        rightLabel.setFont(rightLabel.getFont().deriveFont(rightLabel.getFont().getSize()+30f));
        rightLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(rightLabel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel leftLabel;
    private javax.swing.JLabel rightLabel;
    // End of variables declaration//GEN-END:variables

}
