/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ButtonActionPanel.java
 *
 * Created on 07.09.2009, 20:23:48
 */
package ch.tatool.core.display.swing.action;

import java.awt.Component;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Andre Locher
 */
public class ButtonActionPanel extends AbstractActionPanel {

	private static final long serialVersionUID = 4509894213886644302L;
	public List<JButton> buttons = new ArrayList<JButton>();

    /** Creates new form ButtonActionPanel */
    public ButtonActionPanel() {
        initComponents();
        Component[] comps = this.getComponents();
        for (int i = 0; i < comps.length; i++) {
            if (comps[i] instanceof JPanel) {
                JPanel panel = (JPanel) comps[i];
                Component[] compButtons = panel.getComponents();
                for (int j = 0; j < compButtons.length; j++) {
                    if (compButtons[j] instanceof JButton) {
                        JButton button = (JButton) compButtons[j];
                        buttons.add(button);
                    }

                }

            }
        }
    }

    public void setButtonText(int index, String text) {
        if (buttons.size() > index) {
            buttons.get(index).setText(text);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();

        setOpaque(false);
        setLayout(new java.awt.GridLayout(1, 3, 100, 0));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(5, 0, 0, 5));

        jButton1.setFont(jButton1.getFont().deriveFont(jButton1.getFont().getSize()+6f));
        jButton1.setText("Onkel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setFont(jButton2.getFont().deriveFont(jButton2.getFont().getSize()+6f));
        jButton2.setText("Grossonkel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setFont(jButton3.getFont().deriveFont(jButton3.getFont().getSize()+6f));
        jButton3.setText("Urgrossonkel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        add(jPanel1);

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(5, 0, 0, 5));

        jButton4.setFont(jButton4.getFont().deriveFont(jButton4.getFont().getSize()+6f));
        jButton4.setText("Vater");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);

        jButton5.setFont(jButton5.getFont().deriveFont(jButton5.getFont().getSize()+6f));
        jButton5.setText("Schwiegervater");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);

        jButton6.setFont(jButton6.getFont().deriveFont(jButton6.getFont().getSize()+6f));
        jButton6.setText("Grossvater");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6);

        jButton7.setFont(jButton7.getFont().deriveFont(jButton7.getFont().getSize()+6f));
        jButton7.setText("Urgrossvater");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7);

        jButton8.setFont(jButton8.getFont().deriveFont(jButton8.getFont().getSize()+6f));
        jButton8.setText("Ururgrossvater");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8);

        add(jPanel3);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridLayout(5, 0, 0, 5));

        jButton9.setFont(jButton9.getFont().deriveFont(jButton9.getFont().getSize()+6f));
        jButton9.setText("Bruder");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickActionPerformed(evt);
            }
        });
        jPanel4.add(jButton9);

        jButton10.setFont(jButton10.getFont().deriveFont(jButton10.getFont().getSize()+6f));
        jButton10.setText("Cousin");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10);

        jButton11.setFont(jButton11.getFont().deriveFont(jButton11.getFont().getSize()+6f));
        jButton11.setText("Ehemann");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickActionPerformed(evt);
            }
        });
        jPanel4.add(jButton11);

        jButton12.setFont(jButton12.getFont().deriveFont(jButton12.getFont().getSize()+6f));
        jButton12.setText("Schwager");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickActionPerformed(evt);
            }
        });
        jPanel4.add(jButton12);

        jButton13.setFont(jButton13.getFont().deriveFont(jButton13.getFont().getSize()+6f));
        jButton13.setText("Schwippschwager");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickActionPerformed(evt);
            }
        });
        jPanel4.add(jButton13);

        add(jPanel4);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(5, 0, 0, 5));

        jButton14.setFont(jButton14.getFont().deriveFont(jButton14.getFont().getSize()+6f));
        jButton14.setText("Sohn");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickActionPerformed(evt);
            }
        });
        jPanel2.add(jButton14);

        jButton15.setFont(jButton15.getFont().deriveFont(jButton15.getFont().getSize()+6f));
        jButton15.setText("Schwiegersohn");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickActionPerformed(evt);
            }
        });
        jPanel2.add(jButton15);

        jButton16.setFont(jButton16.getFont().deriveFont(jButton16.getFont().getSize()+6f));
        jButton16.setText("Enkelsohn");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickActionPerformed(evt);
            }
        });
        jPanel2.add(jButton16);

        jButton17.setFont(jButton17.getFont().deriveFont(jButton17.getFont().getSize()+6f));
        jButton17.setText("Urenkelsohn");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickActionPerformed(evt);
            }
        });
        jPanel2.add(jButton17);

        jButton18.setFont(jButton18.getFont().deriveFont(jButton18.getFont().getSize()+6f));
        jButton18.setText("Ururenkelsohn");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickActionPerformed(evt);
            }
        });
        jPanel2.add(jButton18);

        add(jPanel2);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(5, 0, 0, 5));

        jButton19.setFont(jButton19.getFont().deriveFont(jButton19.getFont().getSize()+6f));
        jButton19.setText("Neffe");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickActionPerformed(evt);
            }
        });
        jPanel5.add(jButton19);

        jButton20.setFont(jButton20.getFont().deriveFont(jButton20.getFont().getSize()+6f));
        jButton20.setText("Grossneffe");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickActionPerformed(evt);
            }
        });
        jPanel5.add(jButton20);

        jButton21.setFont(jButton21.getFont().deriveFont(jButton21.getFont().getSize()+6f));
        jButton21.setText("Urgrossneffe");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickActionPerformed(evt);
            }
        });
        jPanel5.add(jButton21);

        add(jPanel5);
    }// </editor-fold>//GEN-END:initComponents

    private void clickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickActionPerformed
        fireActionTriggered(evt.getActionCommand());
    }//GEN-LAST:event_clickActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
